name: Echo Secrets

on: workflow_call
    
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Test
        run: echo "Test"
      - name: Echo Org Secret
        run: |
          echo "Organization Secret => ${{ secrets.TEMP }}"
